### PR TITLE
Verify script and storing raw

### LINKED ISSUE #1657: V8 can't handle 'generate' RPC command when running in 'regtest'
After a clean install of `bitcore v8`, when running in `regtest`, sending a generate command
```
bitcoin-cli -datadir=full-nodes/bitcoin/regtest/ generate 101
```

causes the bitcore-node to behave in an undefined state. The log of the node is as follows:

```
info: Added block 1a4213ca8450217c3270925a9dc47650451d8c8ffe28ed5b3112fec2ce9843ab chain=BTC, network=regtest
info: Added block 43eab1f45bf71508c9dae0fde4e55b77ac00a81c2ed4bfdbd7c037267c3517ef chain=BTC, network=regtest
info: Added block 07886645493302d718cf3dd1e53e79c7e395cf83bb201aa28b5d011e73390af4 chain=BTC, network=regtest
info: Added block 179f07b3fb8a1a14e9496447be070d592a0ecd7d7b80cfd9a8ccbb6f7401d6d9 chain=BTC, network=regtest
info: Added block 464685059f702da9f3cc8f2756ebcba65216f0bab39abd2628fadb157a94476c chain=BTC, network=regtest
info: Added block 60e06e2535fc0b6ddac994e25f5d6dd075a53e945bc3c5b3432679e0815e0a24 chain=BTC, network=regtest
info: Added block 5d42b08a884d9d70847ac34e93e5f2285416992d28430caa7100d82d3e785f6e chain=BTC, network=regtest
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): reorg
info: Added block 44cb18980f357758d9e1b74fad8579749758bdf67ee4012302d0d1e2f10ce373 chain=BTC, network=regtest
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): reorg
info: Added block 3cec06c47ce039dafb89ae3c1c1563cfd06f2119fd318dd34cc0a710e2ef5310 chain=BTC, network=regtest
info: Added block 5ca802a6f4194397ce2cd4ac582caa5814d2d1d5cc8ee30a3a7f0b637b8fe6f0 chain=BTC, network=regtest
info: Added block 374ee2e1b7195a4dd9066978aa8b3668d57c54868a888fe537ac268b8fdc97e9 chain=BTC, network=regtest
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 11): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 17): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 19): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 21): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 23): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 25): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 27): reorg
info: Added block 58c6bf783d4fa045e23b66f5472039e11f46ea744f66d0c1a2b064d7a27e14ff chain=BTC, network=regtest
info: Added block 6a6f31bad2d6c5432ca925e1d187d064e22a3ecba5db7c3860ae510a629d035a chain=BTC, network=regtest
```

The node doesn't crash, but it runs in an undefined state where all blocks have a height of `1` or some weird value

```
$ curl -s localhost:3000/api/BTC/regtest/block | python -m json.tool
[
    {
        "bits": 545259519,
        "chain": "BTC",
        "hash": "39f808449062a5c36bd4b7960748cfa941f99a060dc9a95c267bb856215eaed9",
        "height": 1,
        "merkleRoot": "ece33d615b14d5fbf92611cd5bd14cab366cde81bc545b1d24fc46cef21d536e",
        "network": "regtest",
        "nonce": 0,
        "previousBlockHash": "60a23782bcca01c3edafd431f13c6041207e4358b814244c6ca836ca5ed51b88",
        "reward": 5000000000,
        "size": 227,
        "time": "2018-08-03T13:15:47.000Z",
        "timeNormalized": "2018-08-03T13:15:47.000Z",
        "transactionCount": 1,
        "version": 536870912
    },
    {
        "bits": 545259519,
        "chain": "BTC",
        "hash": "546b235fabbd3789077773acb72cbb2fb4fce341bbbf9f6c751cef64df2ab09d",
        "height": 1,
        "merkleRoot": "5a878a8d30507102fb888ac75c01305c7a7f1568bfdae1d2909fac63eb8e78f9",
        "network": "regtest",
        "nonce": 2,
        "previousBlockHash": "7c6c9654141c312bd9a98e60d751e5e340fea70eee559423728a1273eb785163",
        "reward": 5000000000,
        "size": 227,
        "time": "2018-08-03T13:15:48.000Z",
        "timeNormalized": "2018-08-03T13:15:48.000Z",
        "transactionCount": 1,
        "version": 536870912
    }
]
```

For some reason `reorg` is triggered when it shouldn't. The only alternative now is to generate `1` block at a time.

### LINKED ISSUE #1676: V8 transactions missing input/output coins (Regtest)
This is a weird bug as it doesn't happen very often, but while I'm running the blockExplorer (on `regtest`) and testing the endpoints Asynchronously, sometimes I would end up with a transaction that is missing its inputs on the `bitcore-node`.

In the log below, you can see that the same transaction on `bitcoin-abc` shows fully with the inputs, while on the bitcore-node (using `/tx/:txid/coins` endpoint), you can see that the outputs are correct, while the inputs are missing. 

Unfortunately, I don't yet have a definitive way of reproducing this bug, but I'm fairly certain that it has to do with some race conditions when generating blocks or receiving mempool transactions. 

Could it be caused by the weird `ScriptSig` in the input? Maybe it's crashing some internal component, and hence that input is never processed? 

Do you mind pointing me to where the transaction gets processed (deserialized) after it's received from the `bitcoin-node`?

```json
$ ./full-nodes/BCH/bitcoin-abc-0.17.2/bin/bitcoin-cli -datadir=./full-nodes/BCH/data/ getrawtransaction af46ca91af44fa9e449cdcd6bff53bdd236e589af994065360c99e949d4c1fb7  true
{
  "hex": "0100000001979506f10dc2b94fe95d82549e4c5e320200b3f9ca26929de32a1f897a23a96c00000000fd0b0100473044022043a33f057f89942aaaf4f965f91dadb4c0279365233d78c937dc2f37fb75a491022010cf128bc43946d3e6e6a03bff2c9c8088f575abc783d2e1ced18f5443ae774f41483045022100e926d2204c00e68d3321748ff152555b51ca74c502143e432526da34038aed4102201a1f1e8599268d00412896c81f37a2ead7fb94756725698e9858bf2896efe279414c777453876352210335adf2685c13605a931e5d8ba340cb23fca7c00d7268b8b8ade99d91f26e6af82102aaa4c9bd5799ba59d9b07d9dd346b3278d1cc56978f6d04a2348c2466cffbbbe52ae6704fa297f5bb1752103d98bdcb4e2b90d465273118a984af8ef7765c128688ea1d10802dcdb75c5edefac68ffffffff02a8ba1700000000001976a914e108bbf20b27c485de3145e8eaa1593bb485c26288ac0e290200000000001976a9145bcab8387899aaa223cfd4c29ea6850633c3d40488ac00000000",
  "txid": "af46ca91af44fa9e449cdcd6bff53bdd236e589af994065360c99e949d4c1fb7",
  "hash": "af46ca91af44fa9e449cdcd6bff53bdd236e589af994065360c99e949d4c1fb7",
  "size": 388,
  "version": 1,
  "locktime": 0,
  "vin": [
    {
      "txid": "6ca9237a891f2ae39d9226caf9b30002325e4c9e54825de94fb9c20df1069597",
      "vout": 0,
      "scriptSig": {
        "asm": "0 3044022043a33f057f89942aaaf4f965f91dadb4c0279365233d78c937dc2f37fb75a491022010cf128bc43946d3e6e6a03bff2c9c8088f575abc783d2e1ced18f5443ae774f[ALL|FORKID] 3045022100e926d2204c00e68d3321748ff152555b51ca74c502143e432526da34038aed4102201a1f1e8599268d00412896c81f37a2ead7fb94756725698e9858bf2896efe279[ALL|FORKID] 7453876352210335adf2685c13605a931e5d8ba340cb23fca7c00d7268b8b8ade99d91f26e6af82102aaa4c9bd5799ba59d9b07d9dd346b3278d1cc56978f6d04a2348c2466cffbbbe52ae6704fa297f5bb1752103d98bdcb4e2b90d465273118a984af8ef7765c128688ea1d10802dcdb75c5edefac68",
        "hex": "00473044022043a33f057f89942aaaf4f965f91dadb4c0279365233d78c937dc2f37fb75a491022010cf128bc43946d3e6e6a03bff2c9c8088f575abc783d2e1ced18f5443ae774f41483045022100e926d2204c00e68d3321748ff152555b51ca74c502143e432526da34038aed4102201a1f1e8599268d00412896c81f37a2ead7fb94756725698e9858bf2896efe279414c777453876352210335adf2685c13605a931e5d8ba340cb23fca7c00d7268b8b8ade99d91f26e6af82102aaa4c9bd5799ba59d9b07d9dd346b3278d1cc56978f6d04a2348c2466cffbbbe52ae6704fa297f5bb1752103d98bdcb4e2b90d465273118a984af8ef7765c128688ea1d10802dcdb75c5edefac68"
      },
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 0.01555112,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 e108bbf20b27c485de3145e8eaa1593bb485c262 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a914e108bbf20b27c485de3145e8eaa1593bb485c26288ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "bchreg:qrss3wljpvnufpw7x9z7364ptyamfpwzvgfuyxnfpq"
        ]
      }
    },
    {
      "value": 0.00141582,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 5bcab8387899aaa223cfd4c29ea6850633c3d404 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a9145bcab8387899aaa223cfd4c29ea6850633c3d40488ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "bchreg:qpdu4wpc0zv64g3rel2v984xs5rr8s75qsgype2zz7"
        ]
      }
    }
  ],
  "blockhash": "0d2520aa29398b60522eaec4552a9205f3d9bca7e8189cb291ada41c58591b94",
  "confirmations": 135,
  "time": 1534456767,
  "blocktime": 1534456767
}

$ curl -s localhost:3000/api/BCH/regtest/tx/af46ca91af44fa9e449cdcd6bff53bdd236e589af994065360c99e949d4c1fb7/coins | python -m json.tool{
    "inputs": [],
    "outputs": [
        {
            "address": "bchreg:qrss3wljpvnufpw7x9z7364ptyamfpwzvgfuyxnfpq",
            "coinbase": false,
            "script": {
                "asm": "OP_DUP OP_HASH160 e108bbf20b27c485de3145e8eaa1593bb485c262 OP_EQUALVERIFY OP_CHECKSIG",
                "type": "Pay to public key hash"
            },
            "txid": "af46ca91af44fa9e449cdcd6bff53bdd236e589af994065360c99e949d4c1fb7",
            "value": 1555112,
            "vout": 0
        },
        {
            "address": "bchreg:qpdu4wpc0zv64g3rel2v984xs5rr8s75qsgype2zz7",
            "coinbase": false,
            "script": {
                "asm": "OP_DUP OP_HASH160 5bcab8387899aaa223cfd4c29ea6850633c3d404 OP_EQUALVERIFY OP_CHECKSIG",
                "type": "Pay to public key hash"
            },
            "txid": "af46ca91af44fa9e449cdcd6bff53bdd236e589af994065360c99e949d4c1fb7",
            "value": 141582,
            "vout": 1
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by micahriggan**
closes #1657 
closes #1666 
closes #1676

### CODE REVIEW

**Comment by micahriggan** [comment]
Will investigate the test failure related to reorg to see if it's actually a failure

File: packages/bitcore-node/src/services/p2p.ts [hunk 1]
```diff
@@ -98,13 +99,18 @@ export class P2pService {
...
         this.events.emit(hash, message.block);
         if (!this.syncing) {
-          try {
-            await this.processBlock(block);
-            this.events.emit('block', message.block);
-          } catch (err) {
-            logger.error(`Error syncing ${chain} ${network}`, err);
-            this.sync();
-          }
+          await this.blockProcessLock;
```
Comment (osagga) [inline packages/bitcore-node/src/services/p2p.ts]: This was the problem! there was a race condition on `processBlock` that would throw two `reorg` errors where the second `reorg` error drops the tip that sync has constructed, causing multiple blocks to be lost.  

Ironically, I arrived at the same conclusion just after I posted the follow up comment on #1657. My fix (54ce5f7944c31fe72bc8a421c1f84fcb6ea777cf) used a lock inside of `this.processBlock(block)` the same way `this.sync()` is locked. 

Is this approach better than just locking processBlock from the inside?

File: packages/bitcore-node/src/models/block.ts [hunk 2]
```diff
@@ -136,17 +138,30 @@ export class Block extends BaseModel<IBlock> {
...
       return false;
     }
     if (!localTip || localTip.height === 0) {
       return false;
     }
-    logger.info(`Resetting tip to ${localTip.previousBlockHash}`, { chain, network });
-    await this.collection.deleteMany({ chain, network, height: { $gte: localTip.height } });
-    await TransactionModel.collection.deleteMany({ chain, network, blockHeight: { $gte: localTip.height } });
-    await CoinModel.collection.deleteMany({ chain, network, mintHeight: { $gte: localTip.height } });
+    if (header) {
```
Comment (osagga) [inline packages/bitcore-node/src/models/block.ts]: This if statement logic here is not needed since it throws a lot of useful blocks (why `100`?) and introduces a lot of delay to sync up at least the `100` blocks that were dropped. It highly impacts the performance. The previous logic of just dropping the tip block and relying on `p2p.sync()` works fine I think.

File: packages/bitcore-node/src/models/transaction.ts [hunk 3]
```diff
@@ -25,6 +25,7 @@ export type ITransaction = {
   fee: number;
   size: number;
   locktime: number;
+  raw: string;
```
Comment (osagga) [inline packages/bitcore-node/src/models/transaction.ts]: This `raw` value should be part of the `_apiTransform` return object so that the API actually returns it.

File: packages/bitcore-node/src/models/block.ts [hunk 4]
```diff
@@ -23,6 +23,7 @@ export type IBlock = {
   bits: number;
   reward: number;
   processed: boolean;
+  raw: string;
```
Comment (osagga) [inline packages/bitcore-node/src/models/block.ts]: This `raw` value should be part of the `_apiTransform` return object so that the API actually returns it.

**Comment by osagga** [comment]
@micahriggan Sounds good. 

The problem with dropping 100 is that querying the api twice for a some `txId` will give inconsistent responses (one will give a valid response, and the other will give txId not found). So even though reorg 1000 times might be annoying, but It'll lower the chances of the API response inconsistency since we're only dropping one block at a time.

File: packages/bitcore-node/test/util/verify.ts [hunk 5]
```diff
@@ -58,7 +58,7 @@ export async function blocks(
     expect(block.nonce, 'block nonce').to.equal(truth.nonce);
     expect(block.previousBlockHash, 'block prev hash').to.equal(truth.previousblockhash);
     expect(block.transactionCount, 'block tx count').to.equal(truth.tx.length);
-    expect(block.size, 'block size').to.equal(truth.size);
+    expect(block.size, 'block size').to.lte(truth.size);
```
Comment (micahriggan) [inline packages/bitcore-node/test/util/verify.ts]: These should be wrapped in an if(regtest)

File: packages/bitcore-node/test/util/verify.ts [hunk 6]
```diff
@@ -138,7 +138,7 @@ export async function blocks(
   expect(heights.filter(h => !h).length, 'no duplicate heights').to.equal(0);
 
   // Check increasing times
-  const increases = l => !!l.reduce((prev, curr) => (prev < curr ? curr : undefined));
+  const increases = l => !!l.reduce((prev, curr) => (prev <= curr ? curr : undefined));
```
Comment (micahriggan) [inline packages/bitcore-node/test/util/verify.ts]: regtest only

File: packages/bitcore-node/test/util/verify.ts [hunk 7]
```diff
@@ -159,15 +159,15 @@ export async function transactions(
...
+  while (await txcursor.hasNext()) {
     const tx: ITransaction | null = await txcursor.next();
     if (!tx) {
       break;
     }
     logger.info(`verifying tx ${tx.txid}: ${tx.blockHeight}`);
     const truth = await rpc.transaction(tx.txid, tx.blockHash);
 
-    expect(tx.size, 'tx size').to.equal(truth.size);
+    expect(tx.size, 'tx size').to.lte(truth.size);
```
Comment (micahriggan) [inline packages/bitcore-node/test/util/verify.ts]: regtest only
